name: Build NestJS App on Push

on:
  push:
    branches:
      - '**' # for every branch

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 18, 20 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    container: node:${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Check lint
        run: yarn lint

      - name: Load fixtures
        run: yarn db:clear-load
        env:
          PG_HOST: postgres
          PG_PORT: 5432
          PG_USERNAME: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: postgres


      - name: Run tests
        run: yarn test:e2e
        env:
          PG_HOST: postgres
          PG_PORT: 5432
          PG_USERNAME: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: postgres



    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

