name: Build NestJS App on Push

on:
  push:
    branches:
      - '**' # for every branch

jobs:
  CI:
    runs-on: ubuntu-latest
    env: # setting env variables here makes them available to all steps
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: postgres
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_PREFIX: test
      S3_BUCKET_NAME: test
      S3_REGION: us-east-1
      S3_FORCE_PATH_STYLE: true

    strategy:
      matrix:
        node-version: [ 16, 18, 20 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    container: node:${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Minio mc client and create bucket
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          mv mc /usr/local/bin
          mc config host add minio http://minio:9000 minio minio123
          mc mb minio/test

      - name: Install Dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Check lint
        run: yarn lint

      - name: Load fixtures
        run: yarn db:clear-load

      - name: Run tests
        run: yarn test:e2e

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      minio:
        image: tminformatique/minio-ci:latest
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        ports:
          - 9000:9000
          - 9001:9001
        options: >-
          --health-cmd "curl http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
